
language:
  - rust
rust:
  - 1.16.0
os:
  - linux
  - osx

install: true

script:
  -  python BUILD.py
  - ./bin/blackrose -v
  - ./bin/blackrose -o BlackRoseExamples/HelloWorld.debug.radon BlackRoseExamples/HelloWorld.rose
  - ./bin/blackrose -O -o BlackRoseExamples/HelloWorld.debug.radon BlackRoseExamples/HelloWorld.rose
