
language:
  - rust
rust:
  - 1.16.0
  - beta
  - nightly

os:
  - linux
  - osx

install:
  - make -C BlackRose
  - chmod +x ./bin/blackrose
  - chmod +x ./bin/oldrose

script:
  - ./bin/oldrose -v
  - ./bin/oldrose -o BlackRoseExamples/HelloWorld.debug.radon BlackRoseExamples/HelloWorld.rose
  - ./bin/oldrose -O -o BlackRoseExamples/HelloWorld.debug.radon BlackRoseExamples/HelloWorld.rose

matrix:
  allow_failures:
    - rust: nightly