
language:
  - rust
rust:
  - 1.16.0
  - beta
  - nightly

os:
  - linux
  - osx

install:
  - make theblackrose
  - make radon

script:
  - ./bin/blackrose -v
  - ./bin/blackrose -o BlackRoseExamples/HelloWorld.debug.radon BlackRoseExamples/HelloWorld.rose
  - ./bin/blackrose -O -o BlackRoseExamples/HelloWorld.debug.radon BlackRoseExamples/HelloWorld.rose

matrix:
  allow_failures:
    - rust: nightly